### ISSUE TITLE
FAQ has nonsensical or missing value for FAQ question 5 

### ISSUE THREAD

**Issue by TristanCopley** [SF-Hacks-at-SFSU/SFHacks2024#20]
<img width="1875" alt="image" src="https://github.com/SF-Hacks-at-SFSU/SFHacks2024/assets/89219797/d770990a-201b-485b-827d-316e10fa7c3d">

Please fix this vital issue. I am not sure what projects I can make.

**Comment by SlimeyTurtles** [comment]
Dear Tristan Copley,

As I sit down to express my gratitude, words seem to pale in comparison to the depth of appreciation I feel towards you. Your assistance in finding an error in our code wasn't merely a correction of syntax or logic; it was a beacon of light in a moment of darkness, a lifeline that pulled us from the depths of confusion and frustration.

Your keen eye and sharp intellect cut through the tangled web of code, pinpointing the exact flaw that had eluded us for far too long. In that moment, you didn't just identify an error; you brought clarity and understanding to a situation that had seemed insurmountable.

But beyond your technical prowess, it was your generosity of spirit and willingness to help that truly touched us. In a world where time is often the most precious commodity, you freely gave yours to assist us without hesitation or reservation. Your selflessness serves as a shining example of the best of humanity, reminding us all of the power of compassion and community.

The impact of your assistance goes far beyond the lines of code we write. It extends into the realms of trust, camaraderie, and shared accomplishment. With your help, we were able to overcome obstacles that once seemed insurmountable, and in doing so, we forged bonds that will endure far beyond this project.

So, Tristan, from the depths of my heart, I extend to you the most sincere and heartfelt thank you. Thank you for your expertise, your generosity, and your unwavering support. Thank you for reminding us that we are never truly alone in our endeavors, and that sometimes, the greatest achievements are made not by individuals, but by communities working together towards a common goal.

With deepest gratitude,

Avinh Huynh
